### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JFlin5** [bots-edi/bots#2]
Where is the "Master" documentation going to be kept?

e.g. How do I get this version, and get it to go, on a clean machine?

See several different doc attempts, including:
[bots.readthedocs.io/en/latest/](http://bots.readthedocs.io/en/latest/)
[skilchen.github.io/bots/](http://skilchen.github.io/bots/)

**Comment by lw-schick** [comment]
The documentation http://bots.readthedocs.io/en/latest/ should be right for you - but that is for BOTS version 3.2, not for the version in github. You can download the last stable version at [Sourecforge](https://sourceforge.net/projects/bots/files/bots%20open%20source%20edi%20software/).

[skilchen.github.io/bots/](http://skilchen.github.io/bots/) - this seems to be a documentation from some user wich is probably the same ...

Since the original google code project has been deleted, there is a bit confusing ... we're working with that ...

**Comment by jeffdafoe** [comment]
The docs here http://skilchen.github.io/bots/ seem much more comprehesive than the readthedocs version.

**Comment by JCapriotti** [comment]
Sorry I missed this when I created #4 

@jeffdafoe I agree the `skilchen` version is much better and easier to use. What I have done is:
* Created a docs repo for the documentation "code".
* Created a GitHub Pages repo for the actual built documentation
    * This is viewable at https://bots-edi.github.io/

I thought about moving putting it in RTD, but wanted to keep it simple for now.

**Comment by WouterVH** [comment]
the master documentation are shpinx files in the docs-directory of the bots-repository.
the generated html can be rendered on github via github-pages, on readthedocs.io, or generated just locally

**Comment by WouterVH** [comment]
I think the original question has been answered, so closing this issue.
