### ISSUE TITLE
Documentation Site Not Found Error

### ISSUE THREAD

**Issue by djfurman** [bots-edi/bots#32]
https://bots-edi.github.io/ returns a 404 error for me looking at a clear cache for the documentation. I don't have a lot of experience with GitHub pages, but I'm happy to take a look if somebody can confirm that I'm not the only one seeing this.

**Comment by JCapriotti** [comment]
It got moved to https://bots-edi.github.io/bots/. I think that is a side-effect of putting the GitHub pages in the main repo. 

Its not ideal... it sounds like the end goal is to use RTD, so maybe we should just move it there?

That said... it *might* be fixable according to [this](https://help.github.com/articles/redirects-on-github-pages/). That would involve recreating the bots-edi.github.io repository as sort of a placeholder and putting a redirect so that requests to `/` redirect to `/bots`.
